# Generated by Django 5.1.6 on 2025-03-04 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showing',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='showing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.showing'),
        ),
        migrations.AddField(
            model_name='showing',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.theater'),
        ),
    ]
