# Generated by Django 5.1.6 on 2025-03-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='showing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
